### ISSUE TITLE
PKR_VAR_azure_tags environment variable doesn't apply tags

### ISSUE THREAD

**Issue by lonevvolf** [hashicorp/packer-plugin-azure#196] opened 2022-05-06 12:47 UTC
#### Overview of the Issue

I have set an environment variable PKR_VAR_azure_tags to a value like:
{"tagname": "tagvalue" }
but the created elements do not receive the tags.

#### Reproduction Steps

Set the env variable as above, create resources with packer.

### Plugin and Packer version

packer: 1.8.0

### Simplified Packer Buildfile

https://github.com/actions/virtual-environments/blob/main/images/win/windows2022.json

### Operating system and Environment details

windows2022

### Log Fragments and crash.log files

No relevant logs - resources are provisioned as usual, but no tags

**Comment by nywilken** [comment] 2022-07-22 15:16
Hi @lonevvolf thanks for reaching out. The issue here is that PKR_VAR variables are only auto loaded when using HCL templates. It looks like you are using a JSON template so the workaround here is to load the contents of the environment variable using the `env` function, as you are doing for the other environment variables. 

```json
{
"azure_tags": "{{env `PKR_VAR_azure_tags`}}",
}

```
I'm going to close this issue as it is not a bug in Packer. Please feel free to reach out if you have questions. Cheers!

**Closed by nywilken** 2022-07-22 15:16 UTC
Labels: bug, upstream-packer
