### ISSUE TITLE
Error while publishing an Azure VM Image Version into an Azure Image Definition with TrustedLaunch enabled 

### ISSUE THREAD

**Issue by oliverlabs** [hashicorp/packer-plugin-azure#304] opened 2023-05-30 16:55 UTC
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I need to enable [TrustedLaunch](#) on the VM image.

Unfortunately, I can't do that. Here's the code that I am using for a VM Image Definition:

```
az sig image-definition create -g rg-acg-build `
    -r acg_trla `
    -i 'Trusted_Launch_Image' `
    --features SecurityType=TrustedLaunch `
    -p MicrosoftWindowsServer `
    -f WindowsServer `
    -s 2022-datacenter-g2 `
    --os-type Windows `
    --os-state Generalized `
    --hyper-v-generation V2
```

Here are the options I am using for the HCL Packer file:

```
secure_boot_enabled                 = true
vtpm_enabled                        = true
```

When I do that, the image compiles without problems, but during the Azure Compute Gallery push, I am getting the following error:

```
==> azure-arm.imageBuild: ERROR: -> InternalOperationError : Replication failed in this region due to 'Contract.Assert failed:
Data model DiskEncryptionSetId '' does not match DiskRP returned DiskEncryptionSetId 
'/subscriptions/[redacted]/resourceGroups/RG-ACG-BUILD/providers/Microsoft.Compute/diskEncryptionSets/desPlatform'
```

Any help or ideas are appreciated!

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

latest

### Simplified Packer Template

```
source "azure-arm" "imageBuild" {
  async_resourcegroup_delete = true
  azure_tags = {
    Env               = "Dev"
    "Image Offer"     = "${var.image_offer}"
    "Image Publisher" = "${var.image_publisher}"
    "Image SKU"       = "${var.image_sku}"
    Task              = "Packer"
  }
  build_key_vault_name                = "${var.build_key_vault_name}"
  build_resource_group_name           = "${var.rgName}"
  client_id                           = "${var.client_id}"
  client_secret                       = "${var.client_secret}"
  communicator                        = "winrm"
  disk_encryption_set_id              = "${var.disk_encryption_set_id}"
  image_offer                         = "${var.image_offer}"
  image_publisher                     = "${var.image_publisher}"
  image_sku                           = "${var.image_sku}"
  os_type                             = "Windows"
  secure_boot_enabled                 = true
  vtpm_enabled                        = true
  shared_image_gallery_destination {
    subscription        = "${var.subscription_id}"
    gallery_name        = "${var.acgName}"
    image_name          = "${var.image_name}"
    image_version       = "${var.image_version}"
    replication_regions = ["${var.location}"]
    resource_group      = "${var.rgName}"
  }
  shared_image_gallery_replica_count = 1
  subscription_id                    = "${var.subscription_id}"
  tenant_id                          = "${var.tenant_id}"
  vm_size                            = "${var.vmSize}"
  winrm_insecure                     = true
  winrm_timeout                      = "7m"
  winrm_use_ssl                      = true
  winrm_username                     = "packer"
}

build {
  sources = ["source.azure-arm.imageBuild"]

  provisioner "powershell" {
    inline = ["mkdir C:\\Windows\\Azure", "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit", "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"]
  }

  post-processor "shell-local" {
    execute_command = ["powershell", "-NoProfile", "{{ .Script }}"]
    script          = "packer_pp2.ps1"
```

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by JenGoldstrich** [comment] 2023-05-30 20:42
Hi @oliverlabs this is a duplicate of https://github.com/hashicorp/packer-plugin-azure/issues/264, quoting myself from that issue "since Disk Encryption Set's can only exist in one region if you're replicating a shared image definition to a different region, that DES won't exist in that region", Azure does not support using the same DES across multiple regions, so we would need a unique DES for every region you wanted to replicate this into.  

You can remove the replicated region from your SIG Definition and this should work, please let me know if it doesn't! We would also welcome contributions to support disk encryption sets in multiple locations, but I'm not sure how exactly that works or how Compute Galleries support it so it'd require a bit more investigation

**Comment by oliverlabs** [comment] 2023-05-31 07:31
Thanks for the heads up, @JenGoldstrich. I am happy to contribute if I can. Both the DES and the Compute Gallery _are_ in the same region, West Europe, but it still fails. I guess since this is an array, the plugin fails. Most customer I work with would need replication for at least 2 regions. 

I'll try to remove that option and re-run the script and let you know if the error still persists. 

Side question, but have you come across #305 ? Since most of these DES encrypted images would need to be shared across subscriptions, the VM Image Definitions would need to be done via snapshots and I don't see it supported at present. Could you please have a look? Any ideas?

**Comment by oliverlabs** [comment] 2023-05-31 08:59
So I ran Packer with the replication_regions option commented out and got the same error. I am pretty sure it is to do with Secure Boot option and vTPU option both set to true (which I need to have). I am able to use a DES for a VM Image Definition that has no TrustedLaunch option enabled, but if I create an image definition with Trusted Launch, the code fails. @JenGoldstrich

**Comment by oliverlabs** [comment] 2023-05-31 14:26
any other ideas, @JenGoldstrich ?

**Comment by JenGoldstrich** [comment] 2023-05-31 14:52
Just to be clear when you commented out replicated_regions you still got the following error?

`==> azure-arm.imageBuild: ERROR: -> InternalOperationError : Replication failed in this region due to 'Contract.Assert failed: Data model DiskEncryptionSetId '' does not match DiskRP returned DiskEncryptionSetId '/subscriptions/[redacted]/resourceGroups/RG-ACG-BUILD/providers/Microsoft.Compute/diskEncryptionSets/desPlatform`

I have seen #305 and have assigned it to myself, this is a bit more complex of an ask but its something we want to investigate and see if its something we can prioritize, from the compute gallery UI I can see that we can create an image version from a Disk Snapshot, are you sure this would allow DES encryption across subscriptions? Do you have any Azure documentation about the limitations of cross-subscription DES usage? A lot of features are only supported when directly capturing an image version from a VM instead of a Managed Image, including ARM64 architecture, are these features supported in Disk Snapshot based Compute Gallery image versions?

I'm not sure why you're seeing this error though after removing replicated regions, and I wouldn't expect trusted launch to interfere with what DES ID we send.

**Comment by oliverlabs** [comment] 2023-05-31 16:19
@JenGoldstrich, yes, the same error persists if I comment out the replicated regions option. I am pretty sure it is a bug with Packer as DES value is not being passed to an Azure Compute Gallery, it seems. 

With both commented out `replication_regions = ["${var.location}"]` option and with it, it default to 'westeurope' (e.g. the resource group region). My DES is in the same region, so there should be no conflict.

**Comment by oliverlabs** [comment] 2023-06-01 08:43
@JenGoldstrich, could you confirm how `secure_boot_enabled = true` and `vtpm_enabled = true` flags actually translate to az cli commands to build a Packer temporary VM? When I build a VM manually using az cli, I am able to push to the same Azure Compute Gallery VM Image Definition with no problem. I am using `--encryption-at-host, --os-disk-encryption-set $diskEncryptionSetId --security-type TrustedLaunch` switches. I am fairly certain that the issue is on the Packer azure-arm plugin side and not with my HCL code :)

**Comment by oliverlabs** [comment] 2023-06-01 09:43
@JenGoldstrich , re cross-subscription DES usage limitations: see this https://learn.microsoft.com/en-us/azure/virtual-machines/image-version-encryption#limitations

**Comment by oliverlabs** [comment] 2023-06-01 09:55
Actually, the same paragraph states the following:

> - VM image version source doesn't currently support customer-managed key encryption.

Could it be the culprit @JenGoldstrich ?

**Comment by JenGoldstrich** [comment] 2023-06-01 15:53
I haven't tested this since release but i a certain VM Image version sources were working literally a month ago with disk encryption sets, I was able to use Packer to push to an org that requires double encryption on all images.  So I really don't believe that is the issue.  

I will test this later next week when I have the time and make sure it's still working with or without secure_boot/vtpm enabled.

**Comment by oliverlabs** [comment] 2023-06-01 16:23
Thanks @JenGoldstrich. As mentioned previously, disk encryption sets work as expected when used with a VM Image Definition that has **no Trusted Launch enabled**, if the customised image is pushed to an image definition that does have Trusted Launch enabled as well as has the disk encryption set enabled, you get the error that I described above. 

I'd appreciate if you could test it in your environment. I have tested it with a number of colleagues and they faced the same issue.

For now, we'd have to use a 2-stage workaround that involves having 2 separate Azure Compute Galleries:
![image (2)](https://github.com/hashicorp/packer-plugin-azure/assets/70239916/ba9b925d-23bd-4864-b906-cc51a992bf6b)

It would be great if the Packer azure-arm builder could be modified to (1) take osDisk snapshots prior to (2) pushing to an Azure Compute Gallery with a Trusted Launch VM Image Definition.

**Comment by JenGoldstrich** [comment] 2023-06-21 21:14
Hey @oliverlabs I was able to reproduce this last week with the same error, but interestingly enough while testing potential solutions today I see a new error `ERROR: -> InvalidParameter : The security type 'TrustedLaunchSupported' is not supported for the source id '/subscriptions/[redacted]/resourceGroups/[redacted]/providers/Microsoft.Compute/virtualMachines/pkrvm8m65h64a14'. Currently only Vhd Blob, User Image and Gallery Image Version sources are supported for 'TrustedLaunchSupported' images.` with the following template

```
variable "version" {
  default = "12.0.0"
}

source "azure-arm" "autogenerated_1" {
  communicator        = "winrm"
  image_offer         = "Windows-10"
  image_publisher     = "MicrosoftWindowsDesktop"
  image_sku           = "19h2-pro-g2"
  location            = "West US"
  use_azure_cli_auth  = "true"
  os_type             = "Windows"
  vm_size             = "Standard_DS2_v2"
  winrm_insecure      = "true"
  winrm_timeout       = "3m"
  winrm_use_ssl       = "true"
  winrm_username      = "packer"
  secure_boot_enabled = true
  vtpm_enabled        = true
  shared_image_gallery_destination {
    resource_group       = "jenna"
    gallery_name         = "trusted2"
    image_name           = "trusted"
    image_version        = var.version
    storage_account_type = "Standard_LRS"
  }
}

build {
  provisioner "powershell" {
    inline = [
      "Add-WindowsFeature Web-Server",
      "while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
    ]
  }
  sources = ["source.azure-arm.autogenerated_1"]
}
```

Regardless of Disk Encyrption Set ID, it looks like I can no longer build trusted launch VMs to Azure Compute Galleries, I had previously seen the error you saw when using the combination of DES + Trusted Launch so I'm a bit confused on what is supposed to be supported on Azure, but the new error seems to imply that the right path forward would be to add support for snapshotting VMs to VHDs before publishing those VHDs to a compute gallery as you suggested.  

Can you confirm this new error happens on your end?  Also do you have any contacts who could provide some clarity on what sorts of Compute Gallery images are supported for Trusted Launch, and DES?  I'll reach out to some folks I know in Azure and on our end who might know more. The docs [here](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-portal?tabs=portal%2Cportal2%2Cportal3#trusted-launch-vm-images) imply that you can create Trusted Launch Compute Gallery images from VMs, but this new error I'm getting seems to imply you must first capture them into a disk snapshot

**Comment by oliverlabs** [comment] 2023-06-22 09:21
Thanks for following up on this and great news that you were able to reproduce the error. 

> but the new error seems to imply that the right path forward would be to add support for snapshotting VMs to VHDs before publishing those VHDs to a compute gallery as you suggested.

I agree that that's the best approach forward, @JenGoldstrich. In the meantime, I'll see if I can get further clarifications from my colleagues on the type of images supported for Trusted Launch and DES.

**Comment by oliverlabs** [comment] 2023-06-22 09:32
@JenGoldstrich 

Here's a summary of all combinations I tried:

![packer-tl](https://github.com/hashicorp/packer-plugin-azure/assets/70239916/d5242430-1ab6-4925-a3ae-8cfa0b9c095e)

As you can see from the image above, the _Trusted Launch security type with no DES_ scenario works just fine (as expected) when publishing into an ACG Image Definition with TrustedLaunch enabled.

**Comment by oliverlabs** [comment] 2023-06-23 08:50
@JenGoldstrich, the reason is that you are using the wrong security type. It should be `TrustedLaunch `and not `TrustedLaunchSupported`.

<img width="483" alt="tl" src="https://github.com/hashicorp/packer-plugin-azure/assets/70239916/0e34164b-67ec-49c0-afdf-54cb240b29de">

**Comment by oliverlabs** [comment] 2023-06-23 08:53
@JenGoldstrich do you have an ETA for implementing snapshotting before pushing to a compute gallery functionality? :) I am confident that it would solve the CMK+TL issue.

**Comment by JenGoldstrich** [comment] 2023-06-23 14:49
@oliverlabs Not currently, I am a bit concerned it won't fix the issue fully as it is still unclear in the Azure documentation what types of images support what types of security types, snapshotting into a VHD before publishing to ACG is something I am currently thinking will be part of the v2.0.0 release.  

It is still unclear to my why CMK+TL is not supported currently, but CMK is and TL is, the interplay of those two features only working on some kinds of VMs is something I would like to understand completely before committing to a direction in the plugin. The error that Azure throws does not indicate to me that this should fix the issue, have you heard from folks internally confirming why this combination of features doesn't work?  

You mentioned using the Azure CLI to build this SIG image from a VM successfully, but the Azure CLI wouldn't use a disk snapshot first I don't think, it would just use the VM, which also makes me confused as to why Packer can't do the same.

**Comment by oliverlabs** [comment] 2023-06-26 13:24
@JenGoldstrich, for Azure CLI scenario, I used snapshots from the start. I don't think I tested managed disks with CMK+TL as a source for an image version and I don't think it would work either. I can confirm that the using snapshots definitely works, so I suggest you include this feature in v2.0.0 release :) I have reached out to some of my colleagues to clarify the interplay of CMK and TL and how they might be impacting the image version push. It seems to be a rather niche subject, so I haven't had much success getting to the bottom of it so far.

**Closed** 2023-09-29 14:10 UTC
Labels: bug, regression, sync to jira

**Comment by j7lloyd** [comment] 2024-05-03 15:59
@oliverlabs, I noticed that you closed this issue as completed at the end of September last year. However, I'm encountering the exact same problem with CMK+TL using the latest versions of Packer (1.10.3) and the ARM plugin (2.1.3). Do you have any advice or pointers on how to address this? Your assistance would be greatly appreciated.

**Comment by j7lloyd** [comment] 2024-05-07 07:10
@JenGoldstrich, alternatively, could you please provide an update on this topic?

> @oliverlabs, I noticed that you closed this issue as completed at the end of September last year. However, I'm encountering the exact same problem with CMK+TL using the latest versions of Packer (1.10.3) and the ARM plugin (2.1.3). Do you have any advice or pointers on how to address this? Your assistance would be greatly appreciated.

**Comment by j7lloyd** [comment] 2024-05-23 10:26
@JenGoldstrich, any update on this? And/or can we take VM snapshots before pushing into an Azure Compute Gallery #305?

**Comment by JenGoldstrich** [comment] 2024-05-23 16:06
A couple of things here,

I do not have an update for this issue, it it closed and there has been no activity on it for several months.  A recent contribution added `security_type` as a field, and we were able to create Confidential VMs with CMKs during this work.  

VM snapshots into ACG is not something we have any plans to support, we are open to community contributions on this front, but it is not a priority for us currently.  I do not think this is the solution to the problem you are seeing.

I tested a bit today and got the following error `Encryption Type ConfidentialVmEncryptedWithCustomerKey is not supported for server side encryption with customer managed key.` even when setting my security type to trusted launch, and when verifying the deployment template did not contain ConfidentialVMEncryptedWithCustomerKey, so I am not sure what the issue is here and it'll require further validation, though its possible this is not the error you are seeing, the issue above has several different errors so your message does not make it clear what you are experiencing.

Please open a new issue, with your packer template, and full build output showing what error you're getting, and then I will investigate it further as I am able, but also other community members may have useful information here, opening a new issue helps get more eyes on this.
