### ISSUE TITLE
post-processor failed: unhandled buildvar type []interface {}

### ISSUE THREAD

**Issue by mag009** [hashicorp/packer-plugin-azure#168] opened 2021-11-03 21:12 UTC
I've tested with version 1.7.5 & 1.7.8 and still the same issue

#### Overview of the Issue

```
* Post-processor failed: unhandled buildvar type: []interface {}

==> Wait completed after 7 minutes 31 seconds

==> Some builds didn't complete successfully and had errors:
--> rancher.azure-arm.rancher: 1 error(s) occurred:

* Post-processor failed: unhandled buildvar type: []interface {}
```
==> Builds finished but no artifacts were created.

#### Reproduction Steps

simply add a post-proccessor like the following : 

```
build {
  sources = ["source.azure-arm.rancher"]
  post-processor "manifest" {}
}
```

### Packer version

From `1.7.5+`

worked on version `1.7.2`

**Comment by admssa** [comment] 2021-11-29 08:55
> Does removing the `plan_info` block change the response you get?

The answer is - no, I suppose, as I don't use that block but also experience the issue.

**Comment by gregnorz** [comment] 2022-01-12 17:34
In my testing, this is caused by adding the `shared_image_gallery_destination` block. A simple template that creates a Managed Image and a Shared Image will fail the `manifest` post-processor, but commenting out the `shared_image_gallery_destination` block allows the `manifest` to run and generate correctly.

Example source that fails:
```
source "azure-arm.azure-arm-win-base" {
        name            = "w10-base-acg" # Azure Compute Gallery image

        image_publisher = "MicrosoftWindowsDesktop"
        image_offer     = "windows-10"
        image_sku       = "win10-21h2-ent"

        managed_image_name = "w10-base-managedimage"
        managed_image_resource_group_name = "rg-packertest"

        shared_image_gallery_destination {
            resource_group = "rg-packertest"
            gallery_name = "galimages"
            image_name = "w10-base-imagedef" # Name of the image definition in the Compute Gallery
            image_version = "0.0.1"
            replication_regions = ["centralus"]
        }
    }
```

Example source that succeeds:
```
source "azure-arm.azure-arm-win-base" {
        name            = "w10-base-acg" # Azure Compute Gallery image

        image_publisher = "MicrosoftWindowsDesktop"
        image_offer     = "windows-10"
        image_sku       = "win10-21h2-ent"

        managed_image_name = "w10-base-managedimage"
        managed_image_resource_group_name = "rg-packertest"
    }
```

**Comment by bender-the-greatest** [comment] 2022-01-20 14:27
We are running into this as well when building images with the `azure-arm` builder, but only when deploying the machine image to a shared image gallery within the packer config.

**Comment by milan-musec** [comment] 2022-02-02 10:39
I can confirm same issue here in version 1.7.9 using `azure-arm` and `shared_image_gallery_destination`

**Comment by admssa** [comment] 2022-02-02 17:39
i had to disable the creation of manifests temporarily, to get rid of this error

**Comment by warroyo** [comment] 2022-02-02 19:52
I went to version `1.7.3` to get around this

**Comment by nywilken** [comment] 2022-02-03 16:04
Hi folks, thanks for keeping the thread updated. Apologies for this issue. I think I may have an idea on what might be causing the issue. I will prioritize this for tomorrow.

That said does the error occur when using Packer 1.7.3+ with the Azure packer plugin pinned to 1.0.2? 

You can pin a version of the plugin by using the required_plugins block below. 
```hcl

packer {
  required_plugins {
    azure = {
      version = "= 1.0.2"
      source = "github.com/hashicorp/azure"
    }
  }
}
```

**Comment by nywilken** [comment] 2022-02-04 19:30
Hi folks, I just wanted to give a quick update here. I confirmed this issue is with the Azure plugin starting at version v1.0.3. So pinning to v1.0.2 with the latest version of Packer works as expected. That said the fix requires a little change to the data being captured here https://github.com/hashicorp/packer-plugin-azure/blob/1b232253b6ad17c28513bed69d09e576bbeadfa7/builder/azure/arm/step_publish_to_shared_image_gallery.go#L189. 

I'll work on getting a fix into a PR for folks to test against. But from my local testing and upcoming tests. I've confirmed the bug and the fix.

**Comment by nywilken** [comment] 2022-02-07 23:01
Hello :wave: thanks again for reporting, this should be fixed by #182 ; some test binaries are available via the link below if you would like to test the fix.

https://app.circleci.com/pipelines/github/hashicorp/packer-plugin-azure/153/workflows/e0edb970-c2f0-4363-833a-5decb9e483d8/jobs/2047/artifacts

**Closed** 2022-02-08 09:55 UTC

**Comment by gregnorz** [comment] 2022-02-08 18:43
@nywilken - Thanks for fixing this! I apologize that I haven't had a chance to test for you as I've been on some mission critical tasks. I'll check this out with either your binaries or the next release of Packer.

**Comment by adamevans-ns** [comment] 2022-02-09 10:12
@nywilken, any idea when this will be fully released? I can see this is now in the main branch, but not sure how the packer/plugin release process works. Or will packer pick up the latest plugin version/commit from the main branch if the version isn't pinned?

**Comment by nywilken** [comment] 2022-02-11 19:54
Hi @adamevans-ns great question. I'm pushing out a release for this plugin now and it should be ready for use within the hour. That said, the plugin is being released separately from Packer now that it is maintained in a separate repo. To get the latest version you can use the packer init commad to pull it down. 

The next time Packer core is released this change will be pulled in but we are not planning to release Packer core just yet. So I advise adding the azure plugin as a required plugin to you hcl2 template if you haven't already. Or you can follow the manual install steps documented at https://www.packer.io/plugins

```
packer {
  required_plugins {
    azure = {
      version = ">= 1.0.6"
      source = "github.com/hashicorp/azure"
    }
  }
}
```

FYI we will soon have a separate command `packer plugins` that can be used for installing plugins without the use of `packer init`. It will be available in the next Packer nightly release.
