### ISSUE TITLE
the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group

### ISSUE THREAD

**Issue by hc-github-team-packer** [hashicorp/packer-plugin-azure#172] opened 2021-11-29 11:07 UTC
_This issue was originally opened by @Kunal89SN in https://github.com/hashicorp/packer/issues/11418 and has been migrated to this repository. The original issue description is below._

---
#### Overview of the Issue

I attempted to create a managed image and place it the Azure compute gallery, but it keeps failing with the error message: "the Shared Gallery Image to which to publish the managed image version to does not exist in the resource group", as per the other bug reports, people are saying to pre-create an image definition first, but is there any other workaround or solutions which are in the pipeline ?

Leveraging Packer through Azure DevOps.

**Comment by gregnorz** [comment] 2022-01-12 02:46
If this is the issue I'm thinking of, you at least need to have an Image Definition in the Compute Gallery. Terraform is how I manage that piece, but you can manually create one for testing to see if that solves your problem. Packer won't create the Definition, but it *will* create the Version for you. The docs could probably be updated to indicate this and avoid users running into an error such as yours.

**Comment by nywilken** [comment] 2022-02-08 21:33
Hi @Kunal89SN this issue is a duplicate of #69, and to be honest I don't know if this is something that we would be adding for support as there are multiple ways of creating the Shared Image Gallery. For now, I left a comment with a potential workaround [here](https://github.com/hashicorp/packer-plugin-azure/issues/69#issuecomment-971954816)

@gregnorz recommendation of using Terraform is another great option so we will work on adding that suggestion to the documentation.

**Closed by nywilken** 2022-02-08 21:33 UTC
Labels: docs
